export { Shape } from './Shape'
export { Rectangle } from './Rectangle'
export { Circle } from './Circle'
export { Triangle } from './Triangle'
export { Star } from './Star'
export { Hexagon } from './Hexagon'
